spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.194.203:3306/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '@712717'

server:
  port: 8085

